OS_RELEASE_FIELDS = "\
    ID NAME VERSION BUILD_ID PRETTY_NAME BOARD_TYPE \
"
OS_RELEASE_UNQUOTED_FIELDS:append = " BOARD_TYPE"

BOARD_TYPE = "${MACHINE}"
BUILD_ID = "${@d.getVar('JENKINS_BUILD_ID') or d.getVar('DATETIME')}"
