DISTRO_NAME = "Voyager Linux Minimal"
DISTRO_VERSION = "0.0.1"
SDK_NAME_PREFIX = "voyager-minimal"
SDK_VENDOR = "-voyagerminimalsdk"
SDK_VERSION := "${@'${DISTRO_VERSION}'.replace('snapshot-${METADATA_REVISION}','snapshot')}"
SDK_VERSION[vardepvalue] = "${SDK_VERSION}"
MAINTAINER = "Amarula Solutions <info@amarulasolutions.com>"
TARGET_VENDOR = "-voyagerminimal"

# Set features we want on all AXELERA devices. Also disables any features not
# explicitly mentioned.
DISTRO_FEATURES = " \
  ipv4 \
  ipv6 \
  seccomp \
  systemd \
  usbgadget \
  usbhost \
  wifi \
  zeroconf \
"

LICENSE_FLAGS_ACCEPTED:append = " commercial"

DISTRO_FEATURES_BACKFILL_CONSIDERED += "sysvinit"
VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = "systemd-compat-units"
