#!/usr/bin/env sh
set -e

DATA_DIR="/data"
OVERLAY_DIR="${DATA_DIR}/overlay"

setup_directory_permissions() {
  chown -R root:axelera "${DATA_DIR}"
  chmod -R 775 "${DATA_DIR}"
}

main() {
  setup_directory_permissions
}

main "${@}"
