#@TYPE: Machine
#@NAME: Axelera AXE-SBC-RK3588
#@DESCRIPTION: AXE-SBC-RK3588, the Metis Compute Board, is an SBC designed by Axelera AI.
#https://axelera.ai/evaluation-systems/metis-compute-board

require conf/machine/include/rk3588.inc

KERNEL_DEVICETREE = "rockchip/rk3588-axe-sbc.dtb"
MACHINE_EXTRA_RRECOMMENDS += "kernel-modules"

UBOOT_MACHINE = "axe-sbc-rk3588_defconfig"
PREFERRED_PROVIDER_virtual/kernel = "linux-axelera-mainline"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot"
PREFERRED_VERSION_u-boot = "2026.01"
