header:
  version: 11

distro: voyager
target:
  - voyager-image
  - voyager-image-weston

env:
  WS_APIKEY: ""
  WS_USERKEY: ""

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    commit: 3f88b005244a0afb5d5c7260e54a94a453ec9b3e
    layers:
      .: excluded

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    commit: a270d4c957259761bcc7382fcc54642a02f9fc7d
    layers:
      meta:

  meta-openembedded:
    url: "git://git.openembedded.org/meta-openembedded"
    commit: de8681b4a2a101b99dd2c48d89a7de2ccd9a961f
    layers:
      meta-filesystems:
      meta-oe:
      meta-python:
      meta-networking:

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    commit: b5a1645250c17fb657b7f10166f1c665ce192aaf

  meta-arm:
    url: "git://git.yoctoproject.org/meta-arm"
    commit: 936c02ec13661bd86a05f7f90e1b920d5092d670
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-rockchip:
    url: "ssh://gitea@gitea.amarulasolutions.com:38745/axelera/meta-rockchip.git"
    commit: fb6193a5f5cf80070cf8182c06cb5621433111aa

  meta-mend:
    url: "https://github.com/amarula/meta-mend.git"
    commit: f8012ed4d9abe35ef31a42e0225b8a4954f766ca

  meta-axelera:
    layers:
      meta-axelera:
      meta-axelera/meta-voyager:

local_conf_header:
  meta-axelera: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    INHERIT += " mend cve-check rockchip-image"
    INIT_MANAGER = "systemd"
    IMAGE_INSTALL:append = " android-tools-adbd android-tools-conf-rockchip "
    PREFERRED_PROVIDER_android-tools-conf = "android-tools-conf-rockchip"
    USB_DEBUGGING_ENABLED = "1"
    PACKAGE_CLASSES = "package_deb"
    EXTRA_IMAGE_FEATURES = "debug-tweaks package-management"
    IMAGE_FSTYPES:append = " ${RK_ROOTFS_TYPE} wic wic.gz wic.bmap ext4.gz"
    RK_ROOTDEV_UUID ?= "614e0000-0000-4b53-8000-1d28000054a9"
    RK_ROOTFS_TYPE ?= "ext4"
    WKS_FILE = "generic-gptdisk.wks.in"
    REMOTE_REPOS_PREFIX := "${@bb.utils.contains('USE_GITHUB', '1', 'git://git@github.com/axelera-ai/aisbc.', 'git://gitea@gitea.amarulasolutions.com:38745/axelera/', d)}"
    REMOTE_DRIVER := "${@bb.utils.contains('USE_GITHUB', '1', 'git://git@github.com/axelera-ai/host.pcie-driver.git', 'git://gitea@gitea.amarulasolutions.com:38745/axelera/host.pcie-driver.git', d)}"
    # Mend variables
    WS_WSS_URL = "https://saas-eu.whitesourcesoftware.com/agent"
    WS_PRODUCTNAME = "Axelera"
