header:
  version: 19

signers:
  YoctoBuildandRelease:
    fingerprint: 2AFB13F28FBBB0D1B9DAF63087EB3D32FB631AD9
    gpg_keyserver: keyserver.ubuntu.com
  JonMason:
    fingerprint: A04F5BF5CDD4D89C57F7C9AA6E664BAC7A8BD223
    gpg_keyserver: keyserver.ubuntu.com

distro: voyager
target:
  - voyager-image
  - voyager-image-weston

env:
  WS_APIKEY: ""
  WS_USERKEY: ""
  WS_PRODUCTTOKEN: ""
  WS_AGENT_CONFIG: "/work/meta-axelera/conf/axelera.wss.config"
  JENKINS_BUILD_ID: ""
  WS_PRODUCTNAME: "Axelera"

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    tag: 2022-04.24-kirkstone
    commit: 3f88b005244a0afb5d5c7260e54a94a453ec9b3e
    signed: true
    allowed_signers:
      - YoctoBuildandRelease
    layers:
      .: disabled

  openembedded-core:
    url: "https://git.openembedded.org/openembedded-core"
    tag: 2022-04.24-kirkstone
    commit: a270d4c957259761bcc7382fcc54642a02f9fc7d
    signed: true
    allowed_signers:
      - YoctoBuildandRelease
    layers:
      meta:

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: kirkstone
    commit: de8681b4a2a101b99dd2c48d89a7de2ccd9a961f
    signed: false
    layers:
      meta-filesystems:
      meta-gnome:
      meta-oe:
      meta-python:
      meta-networking:
      meta-multimedia:
      meta-xfce:

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: kirkstone
    commit: b5a1645250c17fb657b7f10166f1c665ce192aaf
    signed: false

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    tag: yocto-4.0.6
    commit: 6b2d97cecd1b0e4bf4caee9a65595d279b57a686
    signed: true
    allowed_signers:
      - JonMason
    layers:
      meta-arm-toolchain:
      meta-arm:

  meta-rockchip:
    url: "ssh://gitea@gitea.amarulasolutions.com:38745/axelera/meta-rockchip.git"
    branch: rk3588
    commit: fb6193a5f5cf80070cf8182c06cb5621433111aa
    signed: false

  meta-mend:
    url: "https://github.com/amarula/meta-mend.git"
    branch: main
    commit: f0f7498a009a06490fadc8a1e64682a8ddeae76d
    signed: false

  meta-axelera:
    layers:
      meta-axelera:
      meta-axelera/meta-voyager:

  axelera-doc:
    url: "ssh://gitea@gitea.amarulasolutions.com:38745/axelera/axelera-doc.git"
    branch: master
    signed: false
    layers:
      .: disabled

local_conf_header:
  meta-axelera: |
    # Some useful lines you may want to copy to your site.conf for development
    # INHERIT += "rm_work"
    INHERIT += " rockchip-image voyager-factoryimg voyager-dataimg"
    INIT_MANAGER = "systemd"
    IMAGE_INSTALL:append = " android-tools-adbd android-tools-conf-rockchip "
    PREFERRED_PROVIDER_android-tools-conf = "android-tools-conf-rockchip"
    USB_DEBUGGING_ENABLED = "1"
    PACKAGE_CLASSES = "package_deb"
    EXTRA_IMAGE_FEATURES = "debug-tweaks package-management"
    IMAGE_FSTYPES:append = " ext4 wic wic.gz wic.bmap ext4.gz"
    RK_ROOTDEV_UUID ?= "614e0000-0000-4b53-8000-1d28000054a9"
    REMOTE_REPOS_PREFIX := "${@bb.utils.contains('USE_GITHUB', '1', 'git://git@github.com/axelera-ai/aisbc.', 'git://gitea@gitea.amarulasolutions.com:38745/axelera/', d)}"
    REMOTE_DRIVER := "${@bb.utils.contains('USE_GITHUB', '1', 'git://git@github.com/axelera-ai/host.pcie-driver.git', 'git://gitea@gitea.amarulasolutions.com:38745/axelera/host.pcie-driver.git', d)}"
    # Mend variables
    WS_WSS_URL = "https://saas-eu.whitesourcesoftware.com/agent"
